export enum ErrorCode {
  ERR_NETWORK = "ERR_NETWORK",
  NOT_VALID_ERROR = "NOT_VALID_ERROR",
  UPLOAD_SIZE_ERROR = "UPLOAD_SIZE_ERROR",

  /* 카테고리 */
  CATEGORY_DELETE_ERROR = "CATEGORY_DELETE_ERROR",
}